import "./globals.css";
import { fontClasses } from "./utils/fonts";
import { AppContextProvider } from "./utils/context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppContextProvider>
      <html lang="en">
        <body className={fontClasses}>{children}</body>
      </html>
    </AppContextProvider>
  );
}
